name: Reservation Bot
on:
  schedule:
    - cron: "1,6,11,16,21,26,31,36,41,46,51,56 * * * *"
    - cron: "3,8,13,18,23,28,33,38,43,48,53,58 * * * *"
    - cron: "5,10,15,20,25,30,35,40,45,50,55 * * * *"
  workflow_dispatch:        # 수동 실행 버튼 활성화

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager requests

      - name: Run Bot
        env:
          MY_ALARM_TOKEN: ${{ secrets.MY_ALARM_TOKEN }}
          MY_CHAT_ID: ${{ secrets.MY_CHAT_ID }}
        run: python page_today.py
